# Generated by Django 2.1.7 on 2020-04-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for deleviry', 'Out for deleviry'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
